### ISSUE TITLE
getImportESM Error

### ISSUE THREAD

**Issue by mzyailqq** [jasnell/piscina#224]
Why use import in npm packages？
Because some configuration files in my project must use require, it is inconvenient to set type to module in package.json。
So I can't solve this error

uncaughtException on process:  Error: Not supported
    at eval (eval at getImportESM (xxxx/node_modules/piscina/dist/src/worker.js:37:27), <anonymous>:1:1)
    at getHandler (xxxx/node_modules/piscina/dist/src/worker.js:58:39)

**Comment by metcoder95** [comment]
@mzyailqq is this still valid?
