### ISSUE TITLE
Error: Cannot find module '.... node_modules\piscina\dist\src\worker.js'

### ISSUE THREAD

**Issue by GugaMagius** [jasnell/piscina#252]
I had this error when execute the package by pkg module (.exe). When I use node locally it works fine.

events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module 'C:\snapshot\serverMES\node_modules\piscina\dist\src\worker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1027:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1459:46)
    at Function.Module._load (internal/modules/cjs/loader.js:896:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:167:24)
    at MessagePort.emit (events.js:315:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
Emitted 'error' event on Piscina instance at:
    at EventEmitterReferencingAsyncResource.runInAsyncScope (async_hooks.js:190:9)
    at Piscina.emit (C:\snapshot\serverMES\node_modules\eventemitter-asyncresource\dist\src\index.js:30:35)
    at Worker.<anonymous> (C:\snapshot\serverMES\node_modules\piscina\dist\src\index.js:471:38)
    at Worker.emit (events.js:315:20)
    at Worker.[kOnErrorMessage] (internal/worker.js:233:10)
    at Worker.[kOnMessage] (internal/worker.js:243:37)
    at MessagePort.<anonymous> (internal/worker.js:164:57)
    at MessagePort.emit (events.js:315:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by rubiin** [comment]
having similar problem in typescript

**Comment by metcoder95** [comment]
Hi! Can you provide some sort of code to see how are you trying to look for the file?
Also, did you try without bundling it?

**Comment by rubiin** [comment]
``` ts
//  thread.ts
import Piscina from 'piscina'

import { resolve } from 'path';

const pool = new Piscina({ filename: resolve(__dirname, 'worker.ts') });

(async () => {
  console.log(await Promise.all([
    pool.run({ a: 2, b: 3 }, { name: 'add' }),
    pool.run({ a: 2, b: 3 }, { name: 'multiply' })
  ]));
})();

```
``` ts
  // worker.ts

export function add ({ a, b }) { return a + b; }
export function multiply ({ a, b }) { return a * b; };

```

**Comment by rubiin** [comment]
my tsconfig:

```json
{
	"compilerOptions": {
		"module": "commonjs",
		"declaration": true,
		"lib": ["es2020"],
		"removeComments": true,
		"emitDecoratorMetadata": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"allowSyntheticDefaultImports": true,
		"target": "es2020",
		"moduleResolution": "node",
		"strictFunctionTypes": true,
		"sourceMap": false,
		"outDir": "./dist",
		"baseUrl": "src",
		"incremental": true,
		"skipLibCheck": true,
		"paths": {
			"@common/*": ["./common/*"],
			"@modules/*": ["./modules/*"],
			"@entities/*": ["./entities/*"],
			"@lib/*": ["./lib/*"]
		}
	},
	"include": ["test/**/*", "src/**/*", "src/entities/application.entity.ts"],
	"types": ["./src/modules/dataloader/dataloader.d.ts"],
	"strict": true,
	"allowUnreachableCode": false,
	"alwaysStrict": true,
	"strictFunctionTypes": true,
	"strictNullChecks": true,
	"isolatedModules": true,
	"forceConsistentCasingInFileNames": true,
	"noUnusedLocals": true,
	"noUnusedParameters": true,
	"noImplicitReturns": true,
	"noFallthroughCasesInSwitch": true,
	"noUncheckedIndexedAccess": true,
	"noPropertyAccessFromIndexSignature": true
}



```

**Comment by rubiin** [comment]
Error:

```

Error: Cannot find module '/home/rubin/Desktop/Projects/backend/Nodejs/takeo/cit-be/dist/common/misc/worker.ts' imported from /home/rubin/Desktop/Projects/backend/Nodejs/takeo/cit-be/node_modules/.pnpm/piscina@3.2.0/node_modules/piscina/dist/src/worker.js
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:437:11)
    at moduleResolve (node:internal/modules/esm/resolve:1009:10)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ESMLoader.import (node:internal/modules/esm/loader:380:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1043:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)



```

**Comment by rubiin** [comment]
@jasnell any updates on this. its really a blocking issue

**Comment by kiliangrashoff** [comment]
I also have this issue while using typescript, and it's blocking me from using Piscina.
Running directly with esbuild-register works fine, but after compiling with tsc the resulting bundle fails with the error:
```
Error: Cannot find module '/build/.yarn/cache/piscina-npm-3.2.0-bab8ec26c3-c1980c7d45.zip/node_modules/piscina/dist/src/worker.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:187:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Piscina instance at:
    at EventEmitterReferencingAsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at Piscina.emit (/build/.yarn/cache/eventemitter-asyncresource-npm-1.0.0-de223b5f00-3cfbbc3490.zip/node_modules/eventemitter-asyncresource/src/index.ts:50:31)
    at Worker.<anonymous> (/build/.yarn/cache/piscina-npm-3.2.0-bab8ec26c3-c1980c7d45.zip/node_modules/piscina/src/index.ts:661:30)
    at Worker.emit (node:events:526:28)
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
    at Worker.[kOnExit] (node:internal/worker:267:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by rubiin** [comment]
Any update on this?

**Comment by rubiin** [comment]
bump

**Comment by excal1bu7** [comment]
> bump

you need to pass path to worker JS file. 
you can use tsc for compile ts to js

**Comment by rubiin** [comment]
> > bump
> 
> you need to pass path to worker JS file. you can use tsc for compile ts to js

That doesnt seem to add up to this examle . https://github.com/piscinajs/piscina/blob/current/examples/typescript/src/index.ts

**Comment by excal1bu7** [comment]
> That doesnt seem to add up to this examle .



> > > bump
> > 
> > 
> > you need to pass path to worker JS file. you can use tsc for compile ts to js
> 
> That doesnt seem to add up to this examle . https://github.com/piscinajs/piscina/blob/current/examples/typescript/src/index.ts

Yea, i thought its another way to set-up piscina with ts. But i'm wrong. Piscina is not working after compiling to commonjs xD

**Comment by excal1bu7** [comment]
> > > bump
> > 
> > 
> > you need to pass path to worker JS file. you can use tsc for compile ts to js
> 
> That doesnt seem to add up to this examle . https://github.com/piscinajs/piscina/blob/current/examples/typescript/src/index.ts

I'm think you problem is you not following the example. You are trying to separate worker file and file where worker used. Example uses only 1 file for all of this.

**Comment by rubiin** [comment]
That  maybe problem in the api relating to typescript. Following the separate worker example but seems like you have to use JS extension which defeats the whole point of using typescript. I will opt for maybe threads.js for now

**Comment by excal1bu7** [comment]
> That maybe problem in the api relating to typescript. Following the separate worker example but seems like you have to use JS extension which defeats the whole point of using typescript. I will opt for maybe threads.js for now

That's why im trying to compile TS to JS first and then run piscina with workers. But it's not working too :( 
Me is too looking at threads

**Comment by metcoder95** [comment]
Hey! Hi, sorry for the delay. Kinda busy days lately.

Yeah, seems like the issue is mostly when doing the lookup for the transpiled file from TS. I think that need to be shaped, sadly it doesn't seem will work for now

**Comment by rubiin** [comment]
I really do love piscinia with all the features it supports out of the box but sadly using it on TS seems to be a chore. I hope ts support will be better in coming versions if there is a plan for it

**Comment by metcoder95** [comment]
I had the chance to make it work and there's a couple of tricks, it's not ideal but maybe something worth it to add.

`index.ts`
```ts
import Piscina from 'piscina'

import { resolve } from 'path';

// @ts-ignore
const pool = new Piscina({ filename: resolve(process.cwd(), 'worker.js') });

(async () => {
  console.log(await Promise.all([
    pool.run({ a: 2, b: 3 }, { name: 'add' }),
    pool.run({ a: 2, b: 3 }, { name: 'multiply' })
  ]));
})();
```

and `worker.ts` can remain the same. Sadly it will only work if previously transpiled, not with runtime tools like `ts-node`.
This is most likely as Piscina needs to have support for being able to resolve such files automatically.
Definitely another way to make it work, but I agree that has better ergonomics if Piscina abstracts this small trick

**Comment by absir1949** [comment]
i have the same problem

**Comment by joelash** [comment]
Has anyone made any progress past this?

**Comment by metcoder95** [comment]
Not yet, the current bandwidth of the team is scarce, but we want to help things move forward. If anyone wants to give it a try, we are happy to support it to make it happen 🙂

**Comment by metcoder95** [comment]
@rubiin can you or someone else provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the issue closely. 🙂

**Comment by nachobibian** [comment]
Isn't this the same issue?
https://github.com/piscinajs/piscina/issues/174

**Comment by metcoder95** [comment]
Could be. @GugaMagius, @rubiin can you confirm the suggested workaround from #174 works for you?
