### ISSUE TITLE
Worker not found after building via webpack

### ISSUE THREAD

**Issue by excal1bu7** [jasnell/piscina#273]
I have to build piscina via webpack, cause i'm using it in electron main process. 
The error is: After build piscina is trying to resolve `worker.js` instead string in `filename` argument:
`const piscina = new Piscina({ filename: "./monitor.worker.js" })`
```
events.js:377
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module '/Users/a/Documents/dev/webpack-piscina-test/dist/worker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:187:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:579:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:403:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Reproduce:
1. Clone https://github.com/RewriteH/webpack-piscina-issue
2. run `yarn` command
3. run `npm run start` command
4. enjoy

**Comment by metcoder95** [comment]
Hi @RewriteH, is this still valid?

**Comment by excal1bu7** [comment]
> Hi @RewriteH, is this still valid?

I think no. Somehow I solved it, but anyway I gave up on piscina and opted for a working pool instead.
