### ISSUE TITLE
piscina with jest

### ISSUE THREAD

**Issue by tuananh** [jasnell/piscina#83]
I have an issue in one of my repo where user uses jest and this issue are pop up from the log

I wonder if it's sth to do with piscina?

```
Jest has detected the following 3 open handles potentially keeping Jest from exiting:

  ●  Piscina

      at new EventEmitterReferencingAsyncResource (../node_modules/eventemitter-asyncresource/src/index.ts:23:5)
      at new EventEmitterAsyncResource (../node_modules/eventemitter-asyncresource/src/index.ts:46:7)
      at new Piscina (../node_modules/piscina/src/index.ts:827:5)
      at Object.<anonymous> (../node_modules/camaro/index.js:4:14)


  ●  WORKER

      at ThreadPool._addNewWorker (../node_modules/piscina/src/index.ts:520:20)
      at ThreadPool._ensureMinimumWorkers (../node_modules/piscina/src/index.ts:514:12)
      at new ThreadPool (../node_modules/piscina/src/index.ts:508:10)
      at new Piscina (../node_modules/piscina/src/index.ts:876:18)
      at Object.<anonymous> (../node_modules/camaro/index.js:4:14)


  ●  MESSAGEPORT

      at ThreadPool._addNewWorker (../node_modules/piscina/src/index.ts:528:30)
      at ThreadPool._ensureMinimumWorkers (../node_modules/piscina/src/index.ts:514:12)
      at new ThreadPool (../node_modules/piscina/src/index.ts:508:10)
      at new Piscina (../node_modules/piscina/src/index.ts:876:18)
      at Object.<anonymous> (../node_modules/camaro/index.js:4:14)
```

ref: https://github.com/tuananh/camaro/issues/113#issuecomment-646836461

**Comment by jasnell** [comment]
Yeah, looks like the pool or messageport aren't being shut down properly. I can't look at the code in Camaro at the moment but that's where I would start looking

**Comment by jasnell** [comment]
Assuming there's nothing left to do here. Can reopen if it turns out that there is.

**Comment by yzld2002** [comment]
Also have this issue, any updates?

**Comment by metcoder95** [comment]
Can you provide a 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?
